# Override the example's SDK INSTALL_DIR with this repo's appropriate submodule
ifneq ($(COM_TI_SIMPLELINK_WIFI_SDK_INSTALL_DIR),)
	COM_TI_SIMPLELINK_WIFI_SDK_INSTALL_DIR:=$(COM_TI_SIMPLELINK_WIFI_SDK_INSTALL_DIR)/simplelink-wifi-sdk
	include $(COM_TI_SIMPLELINK_WIFI_SDK_INSTALL_DIR)/imports.mak
else ifneq ($(SIMPLELINK_WIFI_SDK_INSTALL_DIR),)
	SIMPLELINK_WIFI_SDK_INSTALL_DIR:=$(SIMPLELINK_WIFI_SDK_INSTALL_DIR)/simplelink-wifi-sdk
	include $(SIMPLELINK_WIFI_SDK_INSTALL_DIR)/imports.mak
endif
